trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  entryPoint: 'UserMS/User.Api/User.API.csproj'
  buildConfiguration: 'Release'

steps:
- script: dotnet restore $(entryPoint)
  displayName: 'dotnet restore'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test --configuration $(buildConfiguration) --collect:"XPlat Code Coverage"
  displayName: 'dotnet test $(buildConfiguration)'

- script: dotnet publish --configuration $(buildConfiguration) --output ./publish
  displayName: 'dotnet publish $(buildConfiguration)'
- task: Docker@2
  inputs:
    containerRegistry: 'olegbabkevich DockerHub'
    repository: 'olegbabkevichcoherentsolutions/usermicroservice'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
